baseURL = "https://jessica-herzog.netlify.app/"
languageCode = "en-us"
title = "JH"
theme = "tokiwa"

[params]
description = """
All thoughts creative learning + tech.
"""
favicon = "img/favicon_io/apple-touch-icon.png"
math = true # for introducing $KaTEX$
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
env = "production" # for Google Analytics and DISQUS.
useChineseFonts = false
bannerFont = "fonts/exampleFont"

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"  
    weight = 2

  [[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
[social]
instagram="http://instagram.com/oddlysatisfyingmath"
youtube="https://www.youtube.com/playlist?list=PLgGEde_Quoix4UY39jzMT6t1YvYlHD56z"
github="http://github.com/jessherzog"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"
