baseURL = "https://cranky-mcnulty-c2341f.netlify.app/"
languageCode = "en-us"
title = "JH"
theme = "tokiwa"

[params]
description = """
All thoughts creative learning + tech.
"""
favicon = "img/"
math = true # for introducing $KaTEX$
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
env = "production" # for Google Analytics and DISQUS.
useChineseFonts = false
bannerFont = "fonts/exampleFont"

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"  
    weight = 2

  [[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
[social]
instagram="http://example.com/"
twitter="http://twitter.com/"
youtube="http://youtube.com/"
github="http://github.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"
